version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:8

    working_directory: ~/staycircles-reactnative-expo

    environment:
      BUMP_COMMIT_DESC: "chore - bump App versions"

    steps:
      - checkout
      - run:
          name: Skip when app is bumped
          command: |
            LAST_COMMIT_DESC=$(git show --pretty=format:%s $CIRCLE_SHA1)
            [ "$LAST_COMMIT_DESC" == "$BUMP_COMMIT_DESC" ] && circleci step halt || true
      - run:
          name: Make sure Yarn is installed
          command: 'sudo npm install -g yarn'
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies using Yarn
          command: yarn --ignore-scripts
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Login to expo
          command: yarn run expo login -u "$EXPO_USER" -p "$EXPO_PASS"
      - run:
          name: Publish Changes
          command: yarn run expo publish
      - run:
          name: Create Empty Commit
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "$(git show --pretty=format:%ce $CIRCLE_SHA1)"
            git config user.name "$(git show --pretty=format:%cn $CIRCLE_SHA1)"
            git commit --allow-empty -m "$BUMP_COMMIT_DESC"
            git push -q https://$GITHUB_TOKEN@github.com/yaseenshaik/expo-playground-circleci.git master

workflows:
  version: 2
  publish-job:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master
