version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:8

    working_directory: ~/staycircles-reactnative-expo



    steps:
      - run:
          name: Skip when app is bumped
          command: |
            export GIT_COMMIT_DESC=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            [ "$GIT_COMMIT_DESC" == "Bump version" ] && circleci step halt || true'
      - checkout
      - run:
          name: Make sure Yarn is installed
          command: 'sudo npm install -g yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies using Yarn
          command: yarn --ignore-scripts
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Login to expo
          command: yarn run expo login -u "$EXPO_USER" -p "$EXPO_PASS"
      - run:
          name: Publish Changes
          command: yarn run expo publish
      - run:
          name: Create Empty Commit
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "circle@ci.bot"
            git config user.name "CircleCI Bot"
            git commit --allow-empty -m "Bump version"
            git push -q https://$GITHUB_TOKEN@github.com/yaseenshaik/expo-playground-circleci.git master

workflows:
  version: 2
  publish-job:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master
